### PR TITLE
conv. tm grammar to json. added comment support

### PR DESCRIPTION
**Pull request by cdietrich**
conv. tm grammar to json. added comment support. fixes cdietrich/xtext-languageserver-example#17

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by tsjfd** [comment]
Thx! I have tested your PR but now all highlighting is gone (also keywords). Did I miss something?

**Comment by cdietrich** [comment]
Did you make sure you delete the old extension from  the .vscode/extension folder.

**Comment by cdietrich** [comment]
Bildschirmfoto 2018-11-14 um 06.43.19

**Comment by tsjfd** [comment]
I have removed `~/.vscode` but comments are still not highlighted. I am running latest vscode (version 1.29.0) under Ubuntu 16.04.

image

**Comment by cdietrich** [comment]
how does your .vscode/extension/itemis.... package.json and syntax folder look like?

**Comment by tsjfd** [comment]
.../package.json
```
{
	"name": "xtext-vscode-example",
	"displayName": "Xtext VS Code example",
	"description": "A simple DSL example for VS Code",
	"version": "0.0.17",
	"publisher": "itemis",
	"icon": "images/itemis.png",
	"license": "EPL-1.0",
	"repository": {
		"type": "git",
		"url": "https://github.com/itemis/xtext-languageserver-example.git"
	},
	"bugs": {
		"url": "https://github.com/itemis/xtext-languageserver-example/issues"
	},
	"engines": {
		"vscode": "^1.28.0"
	},
	"categories": [
		"Programming Languages"
	],
	"activationEvents": [
		"onLanguage:mydsl"
	],
	"main": "out/extension",
	"contributes": {
		"languages": [
			{
				"id": "mydsl",
				"aliases": [
					"mydsl"
				],
				"extensions": [
					".mydsl"
				],
				"configuration": "./mydsl.configuration.json"
			}
		],
		"grammars": [
			{
				"language": "mydsl",
				"scopeName": "text.mydsl",
				"path": "./syntaxes/mydsl.tmLanguage.json"
			}
		],
		"commands": [
			{
				"command": "mydsl.a.proxy",
				"title": "MyDsl Command A"
			},
			{
				"command": "mydsl.b",
				"title": "MyDsl Command B"
			}
		]
	},
	"devDependencies": {
		"vscode": "^1.1.21",
		"typescript": "^2.9.2",
		"@types/node": "^10.11.5"
	},
	"dependencies": {
		"vscode-languageclient": "^5.1.0"
	},
	"scripts": {
		"prepublish": "node ./node_modules/vscode/bin/install && tsc -p ./src",
		"compile": "tsc -p ./src",
		"watch": "tsc -w -p ./src",
		"update-vscode": "node ./node_modules/vscode/bin/install"
	},
	"__metadata": {
		"id": "ee7fc7b6-1bc9-46f7-906a-6c9ad492bb80",
		"publisherDisplayName": "itemis AG",
		"publisherId": "6d7228f7-4035-414f-b729-79e55a391c9d"
	}
}
```

.../syntaxes/mydsl.tmLanguage.json
```
{
    "name": "MyDsl",
    "scopeName": "text.mydsl",
    "fileTypes": [
        "mydsl"
    ],
    "repository": {
        "general": {
            "patterns": [
                {
                    "include": "#linecomment"
                },
                {
                    "include": "#blockcomment"
                },
                {
                    "include": "#keyword"
                }
            ]
        },
        "linecomment": {
            "name": "comment.line.double-dash.mydsl",
            "begin": "(^[ \\t]+)?(?=//)",
            "end": "(?=$)"
        },
        "blockcomment": {
            "name": "comment.block.mydsl",
            "begin": "/\\*(\\*)?(?!/)",
            "end": "\\*/"
        },
        
        "keyword": {
            "name": "keyword.control.mydsl",
            "match": "\\b(Hello|from)\\b|!"

        }
    },
    "patterns": [
        {
            "include": "#general"
        }
    ],
    "uuid": "8383e49a-fa0d-4bb5-827b-10e8abb294ca"
}
```

**Comment by cdietrich** [comment]
hmm just tried on linux mint with vscode 1.29

bildschirmfoto vom 2018-11-15 21-55-52

- uninstall the extension
- close vscode
- make sure its deleted from the .vscode/extension folder
- `./gradlew clean build vscodeExtension startCode`

**Comment by cdietrich** [comment]
same here

bildschirmfoto 2018-11-15 um 22 14 53

**Comment by tsjfd** [comment]
I am so stupid. When I tried to figure out why comments are not highlighted I changed the color theme (and by coincidence chose exactly the color theme which colorized comments as grey).

**Comment by cdietrich** [comment]
@kthoms @szarnekow can one of you please review

**Pull request merged**
